#!/usr/bin/env bash


usage() {
cat<<EOF
$0 <build|run> [run-args]

Build or run the integration test docker image.

EOF
}

build() {
  mvn clean deploy \
    -DskipTests \
    -Dexec.skip=true -Dsentinel.skipLaunch=true\
    -P'!standard' \
    -Prelease \
    -Ddocker.skip.push=true \
    -Dmaven.deploy.skip=true \
    -Ddocker.username=$DOCKER_USERNAME \
    -Ddocker.password="$DOCKER_PASSWORD"
}


run() {
  case $(uname) in
    Darwin) THIS_MACHINE="docker.for.mac.localhost";;
    Linux) THIS_MACHINE="localhost";;
    *) echo "Add support for your operating system: $(uname)"; exit 1;;
  esac
  docker run \
    --rm \
    -e K8S_LOAD_BALANCER=$THIS_MACHINE \
    -e K8S_ENVIRONMENT=qa \
    -e SENTINEL_ENV=qa \
    -e CLIENT_KEY=not-needed \
    -e API_KEY=not-needed \
    -e FACILITIES_URL=http://$THIS_MACHINE:8085 \
    -e FACILITIES_API_PATH=/ \
    -e FACILITIES_MANAGEMENT_API_PATH=/ \
    -e FACILITIES_COLLECTOR_URL=http://$THIS_MACHINE:8080 \
    -e FACILITIES_COLLECTOR_API_PATH=/ \
     vasdvp/lighthouse-facilities-tests:latest $@
}

main() {
  local cmd=$1
  shift
  case "$cmd" in
    r|run) run $@;;
    b|build) build;;
    br) build && run $@;;
    *) usage "Unknown command $cmd"
  esac
}


main $@
