#!/usr/bin/env bash

cd $(dirname $(readlink -f $0))

INCLUDE="${1:-.*}"

snatch() {
  echo "========================================="
  local name="$1"
  if [[ ! "$name" =~ $INCLUDE ]]; then echo "Skipping $name"; return 0; fi
  local url="$2"
  local out=src/main/resources/$name.json
  mkdir -p $(dirname $out) > /dev/null 2>&1
  curl -s -w "%{http_code} $name - $out\n" -D /dev/stdout -o $out $url
  if [ ! -f $out ]; then echo "NO REPSONSE" > $out; fi
}

#Wait times and satisfaction scores:
snatch "access-to-care-wait-times" "https://www.accesstocare.va.gov/atcapis/v1.1/patientwaittimes"
snatch "access-to-care-satisfaction" "https://www.accesstopwt.va.gov/Shep/getRawData?location=*"

snatch "state-cemeteries" "https://www.cem.va.gov/cems/cems.xml"

#474 benefits centers, 180 cemeteries, 320 vet centers:
snatch "arcgis-benefits-facilities" "https://services3.arcgis.com/aqgBd3l68G8hEFFE/ArcGIS/rest/services/VBA_Facilities/FeatureServer/0/query?f=json&inSR=4326&outSR=4326&orderByFields=Facility_Number&outFields=*&resultOffset=0&returnCountOnly=false&returnDistinctValues=false&returnGeometry=true&where=1=1"

snatch "arcgis-cemeteries" "https://services3.arcgis.com/aqgBd3l68G8hEFFE/ArcGIS/rest/services/NCA_Facilities/FeatureServer/0/query?f=json&inSR=4326&orderByFields=SITE_ID&outFields=*&outSR=4326&resultOffset=0&returnCountOnly=false&returnDistinctValues=false&returnGeometry=true&where=1=1"

snatch "arcgis-vet-center-facilities" "https://services3.arcgis.com/aqgBd3l68G8hEFFE/ArcGIS/rest/services/VHA_VetCenters/FeatureServer/0/query?f=json&inSR=4326&orderByFields=stationno&outFields=*&outSR=4326&resultOffset=0&returnCountOnly=false&returnDistinctValues=false&returnGeometry=true&where=1=1"

#Drive-time bands:
snatch "pssg-drive-time-bands-0" "https://vhanflwebgistst.v08.med.va.gov/arcgis2/rest/services/Portal/MonthlyVAST_TTB/FeatureServer/0/query?f=json&inSR=4326&outSR=4326&orderByFields=Name&outFields=*&resultOffset=0&returnCountOnly=false&returnDistinctValues=false&returnGeometry=true&where=1=1&resultRecordCount=30"

snatch "pssg-drive-time-bands-1" "https://vhanflwebgistst.v08.med.va.gov/arcgis2/rest/services/Portal/MonthlyVAST_TTB/FeatureServer/0/query?f=json&inSR=4326&outSR=4326&orderByFields=Name&outFields=*&resultOffset=30&returnCountOnly=false&returnDistinctValues=false&returnGeometry=true&where=1=1&resultRecordCount=30"
