@startuml
!include va-colors.iuml

skinparam shadowing false

skinparam {
 ArrowColor<<public>> $PrimaryBlue
 ArrowColor<<internal>> $Red
 RectangleBackgroundColor<<document>> $LightBrightBlue
 RectangleBackgroundColor<<facilities>> $BrightBlue
 DatabaseBackgroundColor<<facilities>> $BrightBlue
 RectangleBackgroundColor<<AWS Lambda cron>> $MediumBrightBlue
 RectangleBackgroundColor<<utility>> $MediumBrightBlue
 DatabaseBackgroundColor<<utility>> $MediumBrightBlue
 RectangleBackgroundColor<<sql package>> $MediumBrightBlue
 RectangleBackgroundColor<<source>> $LightGreen
 RectangleBackgroundColor<<dependency>> $MediumGold
 RectangleBackgroundColor<<partner>> $MediumGreen
 DatabaseBackgroundColor<<dependency>> $MediumGold
 ActorBackgroundColor $White
 ActorBorderColor<<consumer>> $PrimaryBlue
 ActorBorderColor<<facilities>> $Red
}

actor "API Consumer" as CONSUMER <<consumer>>
actor "API Admin" as ADMIN <<facilities>>
rectangle facilties as F <<facilities>>
rectangle "facilities-timer" as TIMER <<AWS Lambda cron>>
database "facilities-operational-db" as DB <<facilities>>
database "Corporate Data Warehouse" as CDW <<dependency>>

rectangle "Access to Care (VHA)" as ATC <<dependency>>
rectangle "Content Management System (CMS)" as CMS <<partner>>
rectangle "Non-National\nCemeteries XML" as CXML <<document>>
rectangle "Website CSV" as WCSV <<document>>
rectangle "Geographer Support Services Center (GSSC) Drive Band" as BANDS <<document>>
rectangle "ETL from A01 to SQL52" as ETL1 <<sql package>>
rectangle "ETL from SQL40 GIS Server to SQL52" as ETL2 <<sql package>>
rectangle "ETL from A06 Raw Service to SQL52" as ETL3 <<sql package>>
rectangle "VHA Support Service Center (VSSC)" as ETL1Source <<source>>
rectangle "Office of Mental Health" as ETL2Source <<source>>
rectangle "Business Intelligence Service Line (BISL)" as ETL3Source <<source>>
rectangle "Veteran Affairs Site Tracking (VAST)" as ETL4Source <<source>>

@enduml
