@startuml
!include component-definitions.iuml!0

CONSUMER <-- F <<public>> : Facilities
ADMIN --> F <<internal>> : Data loading
ADMIN <-- F <<internal>> : Internal data\nrepresentation\nand metrics
TIMER --> F <<internal>> : Reload request
F <--> DB : Facilities\nOperating status\nDrive-time bands
F <- BANDS : Drive-time bands
F <-- CDW : Health facilities\nVeteran centers\nMental health contact\nStop codes
F <-- CXML : Non-National\ncemeteries
F -- WCSV : Facility website URLs
F <-- ATC : Wait times and\nsatisfaction scores
F <-- ARCGIS : National cemeteries\nand benefit centers

ETL -up-> CDW
ETL <-- CDW : Health facilities\nVeteran centers\nMental health contact\nStop codes

CMS -up-> F : Operating status
CMS <-- F : Facility IDs

CDW -[hidden]right- ATC

@enduml
