@startuml
!include component-definitions.iuml!0

CONSUMER <-- F <<public>> : Facilities
ADMIN --> F <<internal>> : Data loading
ADMIN <-- F <<internal>> : Internal data\nrepresentation\nand metrics
TIMER --> F <<internal>> : Reload request
F <--> DB : Facilities\nOperating status\nDrive-time bands
F <- BANDS : Drive-time bands
F <-- CDW : Health facilities\nVeteran centers\nMental health contact\nStop codes\nNational Cemeteries\nBenefit Centers
F <-- CXML : Non-National\ncemeteries
F <-- WCSV : Facility website URLs
F <-- ATC : Wait times\nSatisfaction scores\nClinical Services

ETL1 -up-> CDW
ETL1 <-- CDW : Mental health contact\nStop codes
ETL2 -up-> CDW
ETL2 <-- CDW : National Cemeteries\nBenefit Centers
ETL3 -up-> CDW
ETL3 <-- CDW : Health facilities\nVeteran centers
ETL1Source -up-> ETL1
ETL2Source -up-> ETL1
ETL3Source -up-> ETL2
ETL4Source -up-> ETL3

CMS -up-> F : Operating status\nExtended Services
CMS <-- F : Facility IDs

CDW -[hidden]right- ATC

@enduml
