@startuml
!include component-definitions.iuml!0


CONSUMER <-- F <<public>> : Facilities
ADMIN --> F <<internal>> : Data loading
ADMIN <-- F <<internal>> : Internal data\nrepresentation\nand metrics
TIMER --> F <<internal>> : Reload request
F <-- C : Facilities
F <--> DB : Facilities,operating status,\nand drive time bands
F <- BANDS : Drive time bands
C <-- CDW : Health facilities\nVeteran centers\nMental health\nphone numbers\nand Stop codes
C <-- CXML : State managed\ncemeteries
C -- WCSV : Faciliity website URLs
C <-- ATC : Wait times and\nsatisfaction scores
C <-- ARCGIS : Cemeteries and\nbenefit centers

ETL -up-> CDW
ETL <-- CDW : Health facilities\nVeteran centers\nMental health\nphone numbers\nand Stop codes


CMS -up-> F : Operating status
CMS <-- F : Facility IDs

CDW -[hidden]right- ATC


@enduml
