@startuml
!include component-definitions.iuml!0

CONSUMER -(0- F <<public>> : "/v0/facilities\n/v0/nearby"
ADMIN -(0- F <<internal>> : /internal/management
TIMER -right(0- F <<internal>> : /internal/management/reload
F -- DB
F . BANDS : Manual upload
F -- CDW
F .. CXML
F .. WCSV
F -(0- ATC
ETL1 -up-> CDW
ETL1 <-down- CDW
ETL2 -up-> CDW
ETL2 <-down- CDW
ETL3 -up-> CDW
ETL3 <-down- CDW
ETL1Source -up-> ETL1
ETL2Source -up-> ETL1
ETL3Source -up-> ETL2
ETL4Source -up-> ETL3

CMS -(0- F : /v0/facilities/{id}/cms-overlay\n/facilities/all
CMS -[hidden]up- F
CDW -[hidden]right- ATC
' The hidden connector is to force CMS below F with lollipop in the correct direction
' Without it, the lollipop is rendered backwards.

@enduml
