!$PrimaryBlue="#205493"
!$DarkGray="#323a45"
!$Black="#212121"
!$Gray="#aeb0b5"
!$White="#ffffff"
!$DarkBlue="#112e51"
!$BrightBlue="#02bfe7"
!$Purple="#4c2c92"
!$Gold="#fdb81e"
!$Red="#981b1e"
!$Green="#2e8540"
!$AccountManagementOffice="#fdb71c"
!$EnterpriseDataManagement="#2e8540"
!$EnterpriseProgramManagementOffice="#00a6d2"
!$ITOperationsandServices="#112e51"
!$ITResourceManagement="#e65722"
!$OfficeofInformationSecurity="#323a45"
!$QualityPrivacyRisk="#981b1e"
!$StrategicSourcing="#4c2c92"
!$MediumBlue="#4773aa"
!$MediumBrightBlue="#9bdaf1"
!$MediumGray="#d6d7d9"
!$MediumGold="#f9c642"
!$MediumRed="#e59393"
!$MediumGreen="#4aa564"
!$LightBlue="#dce4ef"
!$LightBrightBlue="#e1f3f8"
!$LightGray="#f1f1f1"
!$LightGold="#fff1d2"
!$LightRed="#f9dede"
!$LightGreen="#e7f4e4"

